### ISSUE TITLE
DanB:  It cant display entry points with long parameter lists.

### ISSUE THREAD

**Issue by shabiel** [shabiel/VPE#11]
Has trouble handling lines with long formal parameter lists. (appx 80
chars)

**Comment by dlwicksell** [comment]
If the entry points + parameter lists are longer than the current margin width of the editor/reader, they work fine, but they do not wrap appropriately, like the rest of the routine lines do. Fixing this will require extensive changes, including potentially complex changes to the syntax highlighting code.

**Comment by shabiel** [comment]
We are going to close this as "won't fix" unless we have somebody interested in the issue.
