### ISSUE TITLE
DanB: Toggle line numbering b/n M vs sequential styles

### ISSUE THREAD

**Issue by shabiel** [shabiel/VPE#14]
Allow line numbering to be either sequential 1through n,  or by line
tag (EN+1, +2, +3, etc..) on-the-fly

**Comment by dlwicksell** [comment]
In the latest version_15.2 development branch, I added the linetag+offset to the ^routine display in the top header. So currently, VPE will display both the line numbers, as well as the line tag and offset, which changes dynamically.

Sam, if you like that change, after you merge it to master, should I close this issue? That will be my plan, unless you want further changes for this issue.

**Comment by shabiel** [comment]
This should take care of this issue. I will close it.
