### ISSUE TITLE
Linda: Routine delete still not working

### ISSUE THREAD

**Issue by lindamry** [shabiel/VPE#22]
This is the version of VPE that I'm using.
XV ; Paideia/SMH,TOAD - Entry point for VPE ; 6/18/16 6:03pm
 ;;13.1;VICTORY PROG ENVIRONMENT;;May 23, 2016

ZR and RDEL don't work. Examples of output attached.
[VPE Routine delete bug.txt](https://github.com/shabiel/VPE/files/335655/VPE.Routine.delete.bug.txt)

**Comment by shabiel** [comment]
Download 13.2 and try again please.

**Comment by shabiel** [comment]
Solved by killing ^XVEMS and re-installing VPE.
