### ISSUE TITLE
VPE Limit on DUZ: 999999

### ISSUE THREAD

**Issue by indigote** [shabiel/VPE#27]
VPE appears to have a limitation for the size of DUZ. I have seen the issue when the DUZ is larger that 6 digits. If your DUZ is larger than 999999, then you will have to use a smaller number in order to proceed.  This is happening in the classic VPE and Sam Habiel verified that it is also happening in the new version of VPE.  Thanks.

Cesar Rodriguez
indigote@verizon.net

**Comment by shabiel** [comment]
Cesar,

I will try to fix this in the next release.

**Comment by indigote** [comment]
No problem Sam, there is no hurry on my end.  Thanks for the heads up.
 indigote at verizon dot net
megabyte is what sharks do to swimmers!!!
