### ISSUE TITLE
PWP:Routine editor save date format enhancement

### ISSUE THREAD

**Issue by qzect32** [shabiel/VPE#46]
When using ..E to edit routines the date and time  that is saved to the 1st line of the routine
in the 3rd piece from the ";" is saved as a MM/DD/YY HR:MMam/pm and should be saved as
a MMM DD, YYYY@HR:MMam/pm 
*find the code that saves the date and time the routine was saved
*and stick this in that spot  $$FMTE^XLFDT($$NOW^XLFDT)

SAC# 2.2.1. The first line of a routine must be in the following format: routine name<ls>; site/programmer<space>-<space>brief description [optional space];date of last edit [update is optional].Date and Time format shall be MMM DD, YYYY@H[H]:MM and may be obtained using existing Kernel date utilities. S Y=$$FMTE^XLFDT($$NOW^XLFDT) The local variable Y will be returned with the formatted date. ZZAA12 ;DALOI/XXX – Example Routine; MAY 01, 2017@13:36

these 3 date types are the most common to see being used on the first line of a routine
7/9/19 10:52am
Jul 9, 2019@10:52am
07/09/2019@10:52am

**Comment by shabiel** [comment]
Thank you for the Report. We will fix this.

**Comment by qzect32** [comment]
ZZMULTITOOL ;PWP/Description ;Jul 11, 2019@9:33:19 [correct]
ZZMULTITOOL ;PWP/Description ; JUL 11, 2019@9:33:19 [wrong]

change the month's for this type to.

MONTH="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec"
there is a trailing space following the coma
almost there...

**Comment by shabiel** [comment]
Fixed in 15.2 branch.
