### ISSUE TITLE
Sam: On Cache, backspacing on first character of tag crashes syntax highlighting

### ISSUE THREAD

**Issue by shabiel** [shabiel/VPE#47]
Error is:
```
<ILLEGAL VALUE>SYNTAX+38^XVEMSYN
```
The problem is that $X gets set to -1 when you delete the last character of a tag, resulting in a crash on Cache. Setting $X to -1 on GT.M has no effect.

**Comment by dlwicksell** [comment]
This will be fixed in a commit on the version_15.2 branch sometime soon.

**Comment by dlwicksell** [comment]
This is fixed in the version_15.2 branch. I'll close this issue when that branch is merged in to master.
