### ISSUE TITLE
Payne: Syntax Highlighting in Cache terminal Error.

### ISSUE THREAD

**Issue by qzect32** [shabiel/VPE#48]
Foreward: The code is a little  non-work releated utility I'm working on that analyzes the routine file (which is common to all routines)....

In a 80x24 Windows cache Terminal the Syntax highlighting works when the editor opens 1 routine initially (if the cursor is left in the default position), if one happens to scroll down the colors change completely to Blue (Comment Region) for the function code code (and not the tag which remains default) when pressing the UP arrow to scroll in the Editor.

 once the cursor reaches the top of the routine the color will change on DOWN arrow 40  characters from the left of the terminal screen. to a yellow 10 characters from the left, magenta @(11 chars), cyan@(12-13 chars),green@(14 chars),magenta@(15-18
 When (ON-Click) of the terminal window is performed the colors will change again into an inconsistent format.

Initial opening of the routine
![image](https://user-images.githubusercontent.com/21374077/61304858-d2dc0880-a7b7-11e9-8cb0-8d77c141dd93.png)

![image](https://user-images.githubusercontent.com/21374077/61303768-12a1f080-a7b6-11e9-91d0-01f69a505c74.png)

onclick
![image](https://user-images.githubusercontent.com/21374077/61303965-644a7b00-a7b6-11e9-83d8-28e3a8443078.png)

scrolling up
![image](https://user-images.githubusercontent.com/21374077/61304106-9f4cae80-a7b6-11e9-803e-8ff7668703a0.png)

scrolling up and down repeatedly changed to this through multiple passes lines 20-29
![image](https://user-images.githubusercontent.com/21374077/61304224-d58a2e00-a7b6-11e9-812a-a69def178970.png)

**Comment by dlwicksell** [comment]
This is the second report I have heard about this. I have never used the Cache Cube terminal before looking at this. This issue does not happen in Linux, using either YottaDB/GT.M or Cache, nor does it happen in Windows using another terminal, at least not that I have found.

I don't normally work in Windows, so had not seen this before. I will try to fix this. Thank you.

**Comment by shabiel** [comment]
Payne,

I honestly think you should move to using Putty. Not only will you get
the syntax highlighting, but you will also get a lot of screen space
as VPE can now take up as many columns as you want on the screen.

--Sam

**Comment by qzect32** [comment]
while I don't have a problem running PuTTY it is not approved by the VA's OI&T Technical Resource manual which is not a show stopper for off-site use but, you need to fix this for Cache Terminal if you expect to release VPE to the VA in the future. 
to my knowledge SecureCRT is approved by OI&T but I don't have a license for it.

**Comment by dlwicksell** [comment]
No worries. I assigned this issue to me, and started looking at it yesterday. I'll do what I can.

**Comment by qzect32** [comment]
Thanks Dave

**Comment by dlwicksell** [comment]
You're welcome.

**Comment by dlwicksell** [comment]
qzect32:

I fixed this issue, but it wasn't a simple thing. You will probably see a bit of flickering when using syntax highlighting in Cache Terminal, depending upon how performant your system is. In order to test this before VPE version 15.2 is released, checkout branch version_15.2.

Let me know how it works for you. I'll close this issue after the pull request is merged in to master.

**Comment by shabiel** [comment]
Fix in 15.2 branch.
