### ISSUE TITLE
Payne: {Syntax highlighting=toggled}&{default timeout=999999}  carriage return occurs BEFORE timeout boundary

### ISSUE THREAD

**Issue by qzect32** [shabiel/VPE#49]
{Syntax highlighting=toggled}&{default timeout=999999}  carriage return occurs earlier than the timeout boundary
I think the superseding timeout might be (299<x<600) be on the lookout...

I first noticed this when performing maintenance on routines performed from the ..RSEARCH function I left the search results in active while fixed each search result..which write to the screen followed by an carriage return / [ENTER] 
I left the terminal open to grab lunch (30-45 mins) and noticed  my previous results were maybe 5-15 results away from where they were previously

this same behavior has occurred at the terminal screen.
leaving a trail of ">>" down the terminal window.
as a false positive test I've put the following command into my spare terminal window
>>W $H
and left the same command in that window with Syntax highlighting off.

**Comment by qzect32** [comment]
can confirm that it only happens when syntax highlighting is on

**Comment by dlwicksell** [comment]
I've seen this behavior on versions before syntax highlighting was added, and at least on YottaDB or GT.M on Linux, I get this same behavior whether syntax highlighting is turned on or off. I believe the timeout here does not respect the custom user-defined timeout, but is instead hard-coded. But I'll have to look at it more in-depth to confirm that.
