### ISSUE TITLE
15.2 fails to install in YottaDB r1.34

### ISSUE THREAD

**Issue by CoherentLogic** [shabiel/VPE#64]
Upon entering `S DUZ=1 D ^XV` on a fresh system:

```
Enter ID Number: 1Error Occurred during Set-up.
ERROR: ERROR+25^XVEMSY:  I XVV("OS")=17!(XVV("OS")=19)!(XVV("OS")=20) D  I 1 ;GTM Mumps/MV1



The emergency error trap was invoked.
Consult your nearest VPE Expert!

Waiting 5 seconds before closing!
```

**Comment by CoherentLogic** [comment]
I should add, the system does have OSEHRA VistA running on it.

**Comment by shabiel** [comment]
@CoherentLogic I will take a look at this some time in the next few weeks. I am moving and have little time. Perhaps @dlwicksell can take a look?

**Comment by dlwicksell** [comment]
Yeah, I can try to take a look soon.

**Comment by shabiel** [comment]
@CoherentLogic I had a brand new Docker Image handy, and I checked this out. I had no problems.

```
>>W $ZYRE
YottaDB r1.35 Linux x86_64
>>..VER

    VPE version 15.2 
```

If you are still interested, put a breakpoint on ERROR+25^XVEMSY and see what `$ZSTATUS` says.

**Comment by gkreis** [comment]
I don't know YottaDB errors or their trapping, but what was/is the value of the XVV("OS") node? Also, enter the line below in immediate mode and see if it executes without an error. 

 I 1 ;

On April 25, 2022 11:04:31 PM EDT, John Willis ***@***.***> wrote:
>Upon entering `S DUZ=1 D ^XV` on a fresh system:
>
>```
>Enter ID Number: 1Error Occurred during Set-up.
>ERROR: ERROR+25^XVEMSY:  I XVV("OS")=17!(XVV("OS")=19)!(XVV("OS")=20) D  I 1 ;GTM Mumps/MV1
>
>
>
>The emergency error trap was invoked.
>Consult your nearest VPE Expert!
>
>Waiting 5 seconds before closing!
>```
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/shabiel/VPE/issues/64
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Greg Kreis
Pioneer Data Systems, Inc.
770-509-2583
http://www.PioneerDataSys.com

Sent from my phone....  typos or nonsense are likely dictation or fat finger errors. :-)

**Comment by shabiel** [comment]
I am closing the issue as I wasn't able to replicate it, and chatted with @CoherentLogic to see if he can reproduce it, and he couldn't at the time. It can be reopened if need be. Thank you @gkreis for chiming in.
