### ISSUE TITLE
DanB:  Has problems when entry points are purely numeric.

### ISSUE THREAD

**Issue by shabiel** [shabiel/VPE#8]
Routine save seems to choke sometimes on numeric subroutine names
(saves routine with bad data)

**Comment by dlwicksell** [comment]
I just tested this, and I have no issue saving a routine with purely numeric entry points. I am testing in the latest version_15.2 development branch. So I need more info, if there is still an issue, as I can't fix an issue that I cannot duplicate. Thanks.

**Comment by shabiel** [comment]
Closing as cannot reproduce.
